"""`robotarm gen-config`: render components/axis_core/src/config_table.c from config/arm.yaml.

Keeps firmware's per-axis config table in sync with the shared config/arm.yaml
that the Python master/simulator also load (see robotarm.config).
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

from robotarm.config import DEFAULT_CONFIG_RELATIVE_PATH, ArmConfig, AxisConfig, load_arm_config

GENERATED_RELATIVE_PATH = "components/axis_core/src/config_table.c"

_HEADER = "/* GENERATED by `uv run robotarm gen-config` from config/arm.yaml -- do not edit. */"


def _repo_root() -> Path:
    """Repo root, found relative to this file's location (pc/robotarm/tools/gen_config.py)."""
    return Path(__file__).resolve().parents[3]


def _f(x: float) -> str:
    """Format a float as a C float literal (repr() round-trips exactly, e.g. `1e-05f`)."""
    return repr(float(x)) + "f"


def _pid_block(kp: float, ki: float, out_min: float, out_max: float, i_min: float, i_max: float) -> str:
    return (
        "{{ .kp = {kp}, .ki = {ki}, .kd = 0.0f, .out_min = {out_min}, .out_max = {out_max}, "
        ".i_min = {i_min}, .i_max = {i_max} }}"
    ).format(kp=_f(kp), ki=_f(ki), out_min=_f(out_min), out_max=_f(out_max), i_min=_f(i_min), i_max=_f(i_max))


def _axis_block(axis: AxisConfig) -> str:
    cpr = axis.counts_per_rad
    pos_min = round(axis.soft_limits_rad[0] * cpr)
    pos_max = round(axis.soft_limits_rad[1] * cpr)
    max_vel = axis.max_velocity_rad_s * cpr
    max_acc = axis.max_accel_rad_s2 * cpr
    max_following_error = round(axis.max_following_error_rad * cpr)

    pos_pid = _pid_block(axis.gains.pos_kp, axis.gains.pos_ki, -max_vel, max_vel, -max_vel * 0.2, max_vel * 0.2)
    vel_pid = _pid_block(
        axis.gains.vel_kp,
        axis.gains.vel_ki,
        -axis.max_duty,
        axis.max_duty,
        -axis.gains.vel_i_limit,
        axis.gains.vel_i_limit,
    )

    home_vel = axis.home.velocity_rad_s * cpr
    home_pos = round(axis.home.position_rad * cpr)
    home_timeout_ms = round(axis.home.timeout_s * 1000)

    return textwrap.dedent(
        f"""\
        {{
            .node_id = {axis.node},
            .name = "{axis.name}",
            .counts_per_rad = {_f(cpr)},
            .max_duty = {_f(axis.max_duty)},
            .pos_min = {pos_min}, .pos_max = {pos_max},
            .max_vel = {_f(max_vel)},
            .max_acc = {_f(max_acc)},
            .max_current_ma = {_f(axis.max_current_ma)},
            .overcurrent_ms = 200,
            .max_following_error = {max_following_error},
            .pos_pid = {pos_pid},
            .vel_pid = {vel_pid},
            .vel_ff = {_f(axis.vel_ff)},
            .home_dir = {axis.home.direction},
            .home_vel = {_f(home_vel)},
            .home_pos = {home_pos},
            .home_current_ma = {_f(axis.home.current_ma)},
            .home_timeout_ms = {home_timeout_ms},
            .motor_sign = {axis.motor_sign}, .encoder_sign = {axis.encoder_sign},
            .watchdog_ms = {axis.watchdog_ms},
        }}"""
    )


def render_config_table(cfg: ArmConfig) -> str:
    blocks = ",\n".join(_axis_block(a) for a in cfg.axes)
    body = textwrap.indent(blocks, "    ")
    return (
        f"{_HEADER}\n"
        '#include "axis/config_table.h"\n'
        "#include <stddef.h>\n"
        "\n"
        "const axis_config_t AXIS_CONFIGS[] = {\n"
        f"{body},\n"
        "};\n"
        "\n"
        "const unsigned AXIS_CONFIG_COUNT = sizeof(AXIS_CONFIGS) / sizeof(AXIS_CONFIGS[0]);\n"
        "\n"
        "const axis_config_t *axis_config_for_node(uint8_t node) {\n"
        "    for (unsigned i = 0; i < AXIS_CONFIG_COUNT; i++) {\n"
        "        if (AXIS_CONFIGS[i].node_id == node) return &AXIS_CONFIGS[i];\n"
        "    }\n"
        "    return NULL;\n"
        "}\n"
    )


def _run(args: argparse.Namespace) -> int:
    repo_root = _repo_root()
    cfg = load_arm_config(repo_root / DEFAULT_CONFIG_RELATIVE_PATH)
    content = render_config_table(cfg)
    out_path = repo_root / GENERATED_RELATIVE_PATH

    if args.check:
        current = out_path.read_text() if out_path.exists() else None
        if current != content:
            print(f"{out_path} is out of date; run `uv run robotarm gen-config`", file=sys.stderr)
            return 1
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    print(f"wrote {out_path}")
    return 0


def register(subparsers: argparse._SubParsersAction) -> None:
    parser = subparsers.add_parser(
        "gen-config",
        help="generate components/axis_core/src/config_table.c from config/arm.yaml",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the generated file on disk differs, instead of writing it",
    )
    parser.set_defaults(func=_run)
