#!/usr/bin/env bash
# Build / flash / monitor the firmware for ONE axis board, with its CAN node id baked in (Ruling R30).
#
#   scripts/build_node.sh N [build]            build into build/nodeN (default action)
#   scripts/build_node.sh N flash -p PORT      flash build/nodeN to the board on PORT
#   scripts/build_node.sh N monitor -p PORT    serial console of that board
#   scripts/build_node.sh N <idf.py args...>   anything else is passed to idf.py (in Docker)
#
# Each node gets its own build directory and its own sdkconfig (build/nodeN/sdkconfig), generated
# from the committed sdkconfig.defaults (USB-JTAG console, TWDT panic, MCPWM in IRAM, ...) plus
# build/nodeN/sdkconfig.node, which this script writes with CONFIG_AXIS_NODE_ID=N. The tracked
# top-level sdkconfig (node 1, used by `scripts/idf.sh build` and the VS Code ESP-IDF extension)
# is never touched.
#
# Building runs idf.py in Docker (scripts/idf.sh). Docker Desktop on macOS cannot pass USB serial
# ports into a container, so on macOS `flash` and `monitor` run on the host instead: esptool
# (via `uvx esptool`) with the build's own flash_args, and pyserial's miniterm for the console.
# On Linux they run idf.py in Docker with the port passed through (--device).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

usage() {
    sed -n '2,7p' "$0" | sed 's/^# \{0,1\}//' >&2
    exit 2
}

[ $# -ge 1 ] || usage
NODE="$1"
shift
case "$NODE" in
    [1-6]) ;;
    *) echo "error: node id must be 1-6, got '$NODE'" >&2; exit 2 ;;
esac
[ $# -ge 1 ] || set -- build

DIR="build/node$NODE"
mkdir -p "$ROOT/$DIR"
printf '# generated by scripts/build_node.sh -- do not edit\nCONFIG_AXIS_NODE_ID=%s\n' "$NODE" \
    > "$ROOT/$DIR/sdkconfig.node"

# The port, for flash/monitor: `-p PORT` / `--port PORT` anywhere in the arguments.
PORT=""
prev=""
for arg in "$@"; do
    if [ "$prev" = "-p" ] || [ "$prev" = "--port" ]; then
        PORT="$arg"
    fi
    prev="$arg"
done

ACTION="$1"
if [ "$(uname -s)" = "Darwin" ] && { [ "$ACTION" = "flash" ] || [ "$ACTION" = "monitor" ]; }; then
    [ -n "$PORT" ] || { echo "error: $ACTION needs -p PORT (e.g. -p /dev/cu.usbmodem1101)" >&2; exit 2; }
    if [ "$ACTION" = "flash" ]; then
        [ -f "$ROOT/$DIR/flash_args" ] || {
            echo "error: $DIR/flash_args not found -- run 'scripts/build_node.sh $NODE build' first" >&2
            exit 2
        }
        cd "$ROOT/$DIR"
        exec uvx esptool --chip esp32s3 -p "$PORT" -b 460800 --before default-reset --after hard-reset \
            write-flash "@flash_args"
    fi
    exec uvx --from pyserial pyserial-miniterm --raw --eol LF "$PORT" 115200
fi

# In Docker: /project is the repo root (see scripts/idf.sh).
if [ -n "$PORT" ]; then
    export IDF_DOCKER_DEVICE="$PORT"
fi
exec "$ROOT/scripts/idf.sh" -B "/project/$DIR" \
    -D SDKCONFIG="/project/$DIR/sdkconfig" \
    -D SDKCONFIG_DEFAULTS="/project/sdkconfig.defaults;/project/$DIR/sdkconfig.node" \
    "$@"
